language: java
notifications:
  email:
    recipients:
      - maciej.hercog@student.put.poznan.pl
      - maria.mikolajczak@student.put.poznan.pl
      - michal.medzin@student.put.poznan.pl
      - wojciech.koszela@student.put.poznan.pl
    on_success: never # default: change
    on_failure: always # default: always

before_deploy:
  - mvn install
  deploy:
    provider: releases
    api_key:
      secure: YOUR_API_KEY_ENCRYPTED
    file: target/bootstrap-builder-2.0.jar
    skip_cleanup: true